### ISSUE TITLE
功能与意见反馈，报bug可以另开issue

### ISSUE THREAD

**Issue by littlecodersh** [littlecodersh/LocalNote#1]
可以在这里交流，我会及时回复的~

**Comment by scavin** [comment]
有 GUI 计划么？

**Comment by littlecodersh** [comment]
@scavin 有的，在通过命令行完善一下程序逻辑和功能以后就出gui

**Comment by scavin** [comment]
记得提醒一下 https://faxian.appinn.com/1714

**Comment by littlecodersh** [comment]
@scavin 好的，谢啦！

**Comment by jay61439476** [comment]
```
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 54] Connection reset by peer
```
安装失败 有遇到过类似的状况吗？

**Comment by littlecodersh** [comment]
@jay61439476 可以另开一个issue，把报错详细的贴一下

**Comment by jay61439476** [comment]
@littlecodersh  印象笔记客户端需要做什么设定吗，我的MD文件以f附件的形式显示了

![image](https://cloud.githubusercontent.com/assets/1329762/15996561/5bf2fccc-315b-11e6-86d5-e6d0b8fc9f82.png)

**Comment by littlecodersh** [comment]
@jay61439476 不需要的，md文档的内容没有显示出来吗？

**Comment by jay61439476** [comment]
@littlecodersh 我的html文件里面如果有图片链接 转出来的md文件会怎么处理

**Comment by littlecodersh** [comment]
@jay61439476 一般会转化成`![title](url)`的形式

**Comment by aizigao** [comment]
楼楼的 笔记貌似不错,,我不懂python 装了3.52 版本然后  , pip install localnote 然后就报错了..

``` shell
$ pip install localnote
Requirement already satisfied (use --upgrade to upgrade): localnote in c:\users\alex\appdata\local\programs\python\python35\lib\site-packages\localnote-1.0.14-py3.5.egg
Collecting requests (from localnote)
  Using cached requests-2.11.0-py2.py3-none-any.whl
Collecting markdown (from localnote)
  Using cached Markdown-2.6.6.zip
Collecting evernote (from localnote)
  Using cached evernote-1.25.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Alex\AppData\Local\Temp\pip-build-oyp625rc\evernote\setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Alex\AppData\Local\Temp\pip-build-oyp625rc\evernote\

```

**Comment by littlecodersh** [comment]
@weixiangzhe 把pip升级一下吧

**Comment by aizigao** [comment]
@littlecodersh  刚在官网下的..已经是8.1.2 版本了..

**Comment by littlecodersh** [comment]
@weixiangzhe 我的问题，刚看见是3.5.2
evernote官方包不支持python3，所以这个软件只能用python2.7

**Comment by aizigao** [comment]
好的..

**Comment by ThomasTommy** [comment]
太棒了，来支持一下！！

**Comment by xshaokun** [comment]
无法登陆印象笔记账号啊

**Comment by littlecodersh** [comment]
@xshaokun 登录过程给我看下

**Comment by xshaokun** [comment]
Damn:mywiki skxie$ localnote init
[INFO] 账户仅需要在第一次使用时设置一次
是否是沙盒环境？[yn] n
是否是国际用户？[yn] n
是否使用开发者Token？[yn] n
Username: xshaokun
Password: 
[INFO] 登录失败

**Comment by zwpaper** [comment]
如果本地和印象笔记都有修改的情况，是会怎么处理呢？

**Comment by hillerliao** [comment]
我也是无法登录。怎么解决？ 和@xshaokun 的问题一模一样。

**Comment by vansin** [comment]
无法登录+1

**Comment by Dawn-K** [comment]
作者有没有更新到python3的想法呢?是什么原因选择了python2?是api的原因吗?

**Comment by vansin** [comment]
更新到python3了，问题已经解决了，但不理解为什么，争取fork一下。



在 2020-02-03 17:16:39，"Dawn-K" <notifications@github.com> 写道：

作者有没有更新到python3的想法呢?是什么原因选择了python2?是api的原因吗?
