### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by skt041959** [littlecodersh/LocalNote#2]
成功登录之后，执行`localnote pull`，能够同步一部分笔记，之后就出现

```
Traceback (most recent call last):
  File "/home/skt/.local/bin/localnote", line 11, in <module>
    sys.exit(main())
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/main.py", line 174, in main
    argDict.get(sys.argv[0], (show_help,))[0](*sys.argv[1:])
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/main.py", line 31, in _check_files_format
    return fn(mainController, *args, **kwargs)
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/main.py", line 106, in pull
    r = mainController.download_notes(False)
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/controllers.py", line 127, in download_notes
    for note in notes: _download_note(noteFullPath + [note[0]])
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/controllers.py", line 102, in _download_note
    contentDict[noteFullPath[1]+'.html'] = self.ec.get_content(noteFullPath)
  File "/home/skt/.local/lib/python2.7/site-packages/LocalNote/evernoteapi/controller.py", line 124, in get_content
    r = self.noteStore.getNoteContent(note.guid)
  File "/home/skt/.local/lib/python2.7/site-packages/evernote/api/client.py", line 138, in delegate_method
    )(**dict(zip(arg_names, args)))
  File "/home/skt/.local/lib/python2.7/site-packages/evernote/edam/notestore/NoteStore.py", line 4385, in getNoteContent
    return self.recv_getNoteContent()
  File "/home/skt/.local/lib/python2.7/site-packages/evernote/edam/notestore/NoteStore.py", line 4411, in recv_getNoteContent
    raise result.systemException
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(errorCode=19, rateLimitDuration=567, _message=None)
```

出现了这个错误之后，就一直登录失败了

**Comment by littlecodersh** [comment]
@skt041959 你看一下FAQ

**Comment by skt041959** [comment]
抱歉了，没注意看

**Comment by littlecodersh** [comment]
@skt041959 没事的，有其他bug欢迎再来提交:)
