### ISSUE TITLE
windows下面在localnote pull出现报错

### ISSUE THREAD

**Issue by wufeng0927** [littlecodersh/LocalNote#6]
`Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\localnote.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\LocalNote\main.py", line 174, in main
    argDict.get(sys.argv[0], (show_help,))[0](*sys.argv[1:])
  File "c:\python27\lib\site-packages\LocalNote\main.py", line 31, in _check_fil
es_format
    return fn(mainController, *args, **kwargs)
  File "c:\python27\lib\site-packages\LocalNote\main.py", line 106, in pull
    r = mainController.download_notes(False)
  File "c:\python27\lib\site-packages\LocalNote\controllers.py", line 127, in do
wnload_notes
    for note in notes: _download_note(noteFullPath + [note[0]])
  File "c:\python27\lib\site-packages\LocalNote\controllers.py", line 102, in _d
ownload_note
    contentDict[noteFullPath[1]+'.html'] = self.ec.get_content(noteFullPath)
  File "c:\python27\lib\site-packages\LocalNote\evernoteapi\controller.py", line
 124, in get_content
    r = self.noteStore.getNoteContent(note.guid)
  File "c:\python27\lib\site-packages\evernote\api\client.py", line 138, in dele
gate_method
    )(**dict(zip(arg_names, args)))
  File "c:\python27\lib\site-packages\evernote\edam\notestore\NoteStore.py", lin
e 4385, in getNoteContent
    return self.recv_getNoteContent()
  File "c:\python27\lib\site-packages\evernote\edam\notestore\NoteStore.py", lin
e 4411, in recv_getNoteContent
    raise result.systemException
evernote.edam.error.ttypes.EDAMSystemException: EDAMSystemException(errorCode=19
, rateLimitDuration=1870, _message=None)`

在window下面执行localnote pull之后，进行更新本地文件出现问题。

**Comment by littlecodersh** [comment]
@wufeng0927 你看一下FAQ

**Comment by littlecodersh** [comment]
@wufeng0927 在新版本中已经增加了错误后明确的提示语，可以更新版本尝试。

``` bash
pip install localnote --upgrade
```
