### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by qinf** [littlecodersh/LocalNote#8]
执行`localnote`命令时，出错：

``` shell
Traceback (most recent call last):
  File "/usr/local/bin/localnote", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/LocalNote/main.py", line 180, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/LocalNote/exception.py", line 9, in _main_wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/LocalNote/main.py", line 179, in _main
    argDict.get(sys.argv[0], (show_help,))[0](*sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/LocalNote/main.py", line 39, in show_help
    print('%-10s: %s'%(fn, h[1].decode('utf8').encode(sys.stdin.encoding)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
```

应该是字符集问题，不知道是我系统的问题还是localnote的问题？

**Comment by littlecodersh** [comment]
@qinf 你是哪个运行环境？

**Comment by qinf** [comment]
@littlecodersh 我用的是docker中的ubuntu 14.04镜像，可能是系统暂时不支持中文的问题。

**Comment by littlecodersh** [comment]
@qinf 你试着运行一下这个命令：`python -c "import sys;print sys.stdin.encoding"`
